apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamestatspubgapi-deployment
  labels:
    app: game-statspubgapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-statspubgapi
  template:
    metadata:
      labels:
        app: game-statspubgapi
    spec:
      containers:
      - name: game-statspubgapi
        image: bangertest.azurecr.io/gamestatspubgapi:v7
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secret-store"
          readOnly: true
      volumes:
      - name: secrets-store01-inline
        csi:
         driver: secrets-store.csi.k8s.io
         readOnly: true
         volumeAttributes:
           secretProviderClass: "azure-gamestatspubgapi-kv"
---
apiVersion: v1
kind: Service
metadata:
  name: game-statspubgapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: game-statspubgapi
