name: Deploy PortalLandingPage to AKS
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        default: latest
        required: true
        
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout source code 
          uses: actions/checkout@v3
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Set AKS context'
          id: set-context
          uses: azure/aks-set-context@v3
          with:
            resource-group: '${{ secrets.RESOURCE_GROUP }}' 
            cluster-name: '${{ secrets.CLUSTER_NAME }}'
        - name: 'Setup kubectl'
          id: install-kubectl
          uses: azure/setup-kubectl@v3
        - name: 'Deploy to AKS'
          id: deploy-aks
          uses: Azure/k8s-deploy@v4
          with:
            namespace: 'default'
            manifests: |
               portallandingpage-deploy.yaml
            images: |
               ${{ secrets.REGISTRY_LOGIN_SERVER }}/portallandingpage:${{ github.event.inputs.version }}
