---
name: Example 2
on: [workflow_dispatch]
jobs:
  build:
    name: Build Docker
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: 6.0.x
    - name: Test dotnet
      run: |
        dotnet
    
