---
name: Example 2
on: [workflow_dispatch]
jobs:
  build:
    name: Build Docker
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
        dotnet
