---
name: Example 2
on: [workflow_dispatch]
jobs:
  build:
    name: Build Docker
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "./.dotnet"
    steps:
    - name: Install a SQL Server suite of tools
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=${{ env.GH_TEST_SQL_SA_PASSWORD }}" -e "MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS" --name sql -p 1433:1433 -d "mcr.microsoft.com/mssql/server:2019-latest"
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build docker
      run: |
        docker build -t test .
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.1
      with:
       dotnet-version: 6.0.x
    - name: Test dotnet
      run: |
        dotnet
    
