name: Mixed inputs

on:
  push:
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF}
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`"
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
