name: Mixed inputs

on:
  workflow_dispatch:
  
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo ${GITHUB_REF}
          echo "GIT_TAG=`echo $(git describe --tags --abbrev=0)`"
