on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Name of a container to deploy to AKS'
        options: 
        - game-statspubgapi
        - game-statspubgspa
        - secretsreader
        required: true
        
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Login to Azure Registry and get container'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            # run: az acr repository show-tags -n bangertest --repository ${{ github.event.inputs.name }}
            run: echo "${{ secrets.REGISTRY_LOGIN_SERVER }}"
            run: echo "${{ toJSON(github.event.inputs) }}"
