name: Deploy to AKS
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: 'Name of a container to deploy to AKS'
        options: 
        - game-statspubgapi
        - game-statspubgspa
        - secretsreader
        - sampleapp
        required: true
      version:
        type: string
        default: latest
        required: true      
        
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: 'Set AKS context'
          id: set-context
          uses: azure/aks-set-context@v3
          with:
            resource-group: '${{ secrets.RESOURCE_GROUP }}' 
            cluster-name: '${{ secrets.CLUSTER_NAME }}'
        - name: 'Setup kubectl'
          id: install-kubectl
          uses: azure/setup-kubectl@v3
        - name: 'Deploy to AKS'
          id: deploy-aks
          uses: Azure/k8s-deploy@v4
          with:
            action: deploy
            namespace: 'default'
            manifests: |
              deploy-${{ github.event.inputs.name }}.yaml
            images: |
              '${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ github.event.inputs.name }}:${{ github.event.inputs.version }}'
